# Generated by Django 2.2.13 on 2021-08-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='titla',
            new_name='title',
        ),
    ]
