# Generated by Django 2.2.13 on 2021-08-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210808_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DR', 'Drinks'), ('FO', 'Food'), ('CL', 'Clothing'), ('AC', 'Acomodation')], default='DR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary '), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
