# Generated by Django 2.2.13 on 2021-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210813_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='test Item', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='test Item', max_length=100),
            preserve_default=False,
        ),
    ]
