# Generated by Django 2.2.13 on 2021-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210817_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='ts-slug'),
            preserve_default=False,
        ),
    ]
