# Generated by Django 2.2.13 on 2021-08-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
